### ISSUE TITLE
ModuleNotFoundError: No module named 'bind'

### ISSUE THREAD

**Issue by gitnepal** [0x00-0x00/ShellPop#10]
After installing requirement, and installing setup still got error !

Traceback (most recent call last):
  File "/usr/local/bin/shellpop", line 4, in <module>
    __import__('pkg_resources').run_script('shellpop==0.3.5', 'shellpop')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 765, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1545, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/shellpop-0.3.5-py3.6.egg/EGG-INFO/scripts/shellpop", line 30, in <module>
    from shellpop import *
  File "/usr/local/lib/python3.6/dist-packages/shellpop-0.3.5-py3.6.egg/shellpop/__init__.py", line 1, in <module>
    from bind import *
ModuleNotFoundError: No module named 'bind'

**Comment by touhidshaikh** [comment]
use python 2.* for this tool..... in your error i clearly see u r using python 3.6 which is not recommended.

**Comment by touhidshaikh** [comment]
i m closing this issue.... if u face any further use ... raise an issue ... we happy to help you. Thanks
