### ISSUE TITLE
Requirements.txt should include netifaces

### ISSUE THREAD

**Issue by lordzarak** [0x00-0x00/ShellPop#8]
Hi there! I'm excited to use this. Thank you so much for your contribution to the community and hard work!!

Just getting started and noticed that a module was missing from requirements.

```
Traceback (most recent call last):
  File "/usr/local/bin/shellpop", line 4, in <module>
    __import__('pkg_resources').run_script('shellpop==0.3.5', 'shellpop')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/shellpop-0.3.5-py2.7.egg/EGG-INFO/scripts/shellpop", line 22, in <module>
    import netifaces
ImportError: No module named netifaces
```

Hope this helps! Thanks again.

**Comment by 0x00-0x00** [comment]
Thanks for your help! I just commited the changes to master branch. I really appreciate it. Thanks, again.
